import LoginForm from "@/components/LoginForm";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata = {
    title: 'Login',
    description: 'Generated by create next app',
}

export default async function Login() {
    const session = await getServerSession(authOptions)
    if (session != null) {
        redirect('/')
    }
    return (<>
        <LoginForm />
    </>)

}