import { Inter } from 'next/font/google'
import { Providers } from '@/app/providers'
import { NavBar } from '@/components/index'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=' bg-gray-100'>
        <NavBar />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
