import { Providers } from '@/app/(user)/providers'
import {NavBar} from "@/components";
import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=' bg-gray-100'>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
